[tool.poetry]
name = "ibtws"
version = "0.1.0"
description = ""
authors = ["Home Workstation <kursus1010@gmail.com>"]
packages = [{ include = "ibtws", from = "src" }]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ib-async = {path = "libs/ib_async"}
ibapi = {path = "libs/twsapi/pythonclient"}

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.6.0"
pytest = "^9.0.2"
pytest-asyncio = "^1.3.0"
vulture = "^2.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["E501"]

[tool.ruff.format]
preview = true
