[tool.poetry]
name = "ibtws"
version = "0.3.6"
description = ""
authors = ["Home Workstation <kursus1010@gmail.com>"]
packages = [{ include = "ibtws", from = "src" }]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ib-async = {git = "https://github.com/bigbossguru/ib_async.git", rev = "v2.1.0"}
pandas = ">=2.3,<4.0"
scipy = "^1.18.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.6.0"
pytest = "^9.0.2"
pytest-asyncio = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["E501"]

[tool.ruff.format]
preview = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
